### ISSUE TITLE
SciView is broken with current scenery

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#108]
Caused by: kotlin.KotlinNullPointerException

	at graphics.scenery.backends.opengl.OpenGLRenderer$loadTexturesForNode$1.accept(OpenGLRenderer.kt:1817)

	at graphics.scenery.backends.opengl.OpenGLRenderer$loadTexturesForNode$1.accept(OpenGLRenderer.kt:54)

	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)

	at graphics.scenery.backends.opengl.OpenGLRenderer.loadTexturesForNode(OpenGLRenderer.kt:1759)

	at graphics.scenery.backends.opengl.OpenGLRenderer.initializeNode(OpenGLRenderer.kt:1662)

	at graphics.scenery.backends.opengl.OpenGLRenderer.render(OpenGLRenderer.kt:1228)

	at graphics.scenery.backends.opengl.OpenGLRenderer.display(OpenGLRenderer.kt:557)

	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)

	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)

	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)

	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)

	... 7 more

**Comment by kephale** [comment]
This is from trying to run
https://github.com/scenerygraphics/SciView/blob/master/src/main/java/sc/iview/Main.java
which used to work

**Comment by skalarproduktraum** [comment]
Hey @kephale,

sorry for the issue! However, this cannot be a current problem, as the SciView pom is still at `0.1.1-SNAPSHOT`, which has not been updated in quite some time. The issue above however I'll investigate and fix.

Additionally, what about automatic SciView builds when a new scenery build was successful?

**Comment by skalarproduktraum** [comment]
Okay, issues are fixed now, see scenerygraphics/SciView#54.
The culprits were two: Me not handling texture not found in OpenGLRenderer, and you having a hard-coded colormap path in the SciView class, and slf4j-simple not in the POM, so there was no way of knowing.

Sorry again for the inconvenience. I'll close this for now as I believe it's fixed with the PR and the latest scenery snapshot. Feel free to reopen in case I'm mistaken :)
