### ISSUE TITLE
Occasional spirvcrossj error

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#156]
This comes up occasionally, but not always, with a multimodule run of SciView using the latest scenery and imagej-mesh doing just the Volume Render test from SciView

```
[SciJava-5e8fbfcb-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Reading shader from shaders/DefaultDeferred.vert.spv...
Exception in thread "SciJava-5e8fbfcb-Thread-1-FPSAWTAnimator#00-Timer0" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught IndexOutOfBoundsException: vector index out of range on thread SciJava-5e8fbfcb-Thread-1-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught IndexOutOfBoundsException: vector index out of range on thread SciJava-5e8fbfcb-Thread-1-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more
Caused by: java.lang.IndexOutOfBoundsException: vector index out of range
	at graphics.scenery.spirvcrossj.libspirvcrossjJNI.ResourceVec_get(Native Method)
	at graphics.scenery.spirvcrossj.ResourceVec.get(ResourceVec.java:71)
	at graphics.scenery.backends.opengl.OpenGLShaderModule.<init>(OpenGLShaderModule.kt:145)
	at graphics.scenery.backends.opengl.OpenGLShaderModule$Companion.getFromCacheOrCreate(OpenGLShaderModule.kt:364)
	at graphics.scenery.backends.opengl.OpenGLRenderer.prepareShaderProgram(OpenGLRenderer.kt:589)
	at graphics.scenery.backends.opengl.OpenGLRenderer.prepareRenderpasses(OpenGLRenderer.kt:552)
	at graphics.scenery.backends.opengl.OpenGLRenderer.init(OpenGLRenderer.kt:403)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	... 7 more
```

**Comment by skalarproduktraum** [comment]
Seems to be fixed. Please reopen if it occurs again.
