### ISSUE TITLE
Aniso volume render bug (strikes back)

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#172]
Note that I was able to get a larger image to load, but I got this error that is similar to the previous recent aniso volume render bug.
Image specs:
![image](https://user-images.githubusercontent.com/400105/40286165-a6b7a4f8-5c59-11e8-9c7f-2298f46c49b8.png)
Error:
```
[WARNING] Add Volume
Exception in thread "SciJava-791fc759-Thread-6-FPSAWTAnimator#00-Timer0" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught IndexOutOfBoundsException: Required 217703903 remaining bytes in buffer, only had 217403208 on thread SciJava-791fc759-Thread-6-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught IndexOutOfBoundsException: Required 217703903 remaining bytes in buffer, only had 217403208 on thread SciJava-791fc759-Thread-6-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:476)
	at com.jogamp.opengl.GLAutoDrawableDelegate.display(GLAutoDrawableDelegate.java:190)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more
Caused by: java.lang.IndexOutOfBoundsException: Required 217703903 remaining bytes in buffer, only had 217403208
	at com.jogamp.common.nio.Buffers.rangeCheckBytes(Buffers.java:1056)
	at jogamp.opengl.gl4.GL4bcImpl.glTexSubImage3D(GL4bcImpl.java:7979)
	at cleargl.GLTexture.copyFrom(GLTexture.java:501)
	at cleargl.GLTexture.copyFrom(GLTexture.java:520)
	at graphics.scenery.backends.opengl.OpenGLRenderer$loadTexturesForNode$1.accept(OpenGLRenderer.kt:2068)
	at graphics.scenery.backends.opengl.OpenGLRenderer$loadTexturesForNode$1.accept(OpenGLRenderer.kt:58)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at graphics.scenery.backends.opengl.OpenGLRenderer.loadTexturesForNode(OpenGLRenderer.kt:2024)
	at graphics.scenery.backends.opengl.OpenGLRenderer.initializeNode(OpenGLRenderer.kt:1918)
	at graphics.scenery.backends.opengl.OpenGLRenderer.render(OpenGLRenderer.kt:1473)
	at graphics.scenery.backends.opengl.OpenGLRenderer.display(OpenGLRenderer.kt:638)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 8 more
```

**Comment by kephale** [comment]
^^^ (723, 561, 536)

**Comment by skalarproduktraum** [comment]
m( Being able to read is clearly an advantage...

**Comment by skalarproduktraum** [comment]
Turns out checking the total volume size for being alignable doesn't cut it, fix introduced with above commit. Please reopen if the issue still occurs.
