### ISSUE TITLE
Timeout when rendering maximized on hiDPI

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#238]
When trying to do a volume rendering (e.g., GOL3D) while having the rendering window maximized on a hiDPI display, I get timeouts like the following:

```
Creating render framebuffer Viewport for pass FXAA (2893x2028)
^CException in thread "SciJava-299d7c54-Thread-3-FPSAWTAnimator#00-Timer0" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught ThreadDeath: null on thread SciJava-299d7c54-Thread-3-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught ThreadDeath: null on thread SciJava-299d7c54-Thread-3-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more
Caused by: java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:853)
	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook$1.run(GLWindow.java:724)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.newt.opengl.GLWindow$GLLifecycleHook.shutdownRenderingAction(GLWindow.java:719)
	at jogamp.newt.WindowImpl.shutdown(WindowImpl.java:635)
	at jogamp.newt.WindowImpl.shutdownAll(WindowImpl.java:123)
	at jogamp.newt.DisplayImpl$1.run(DisplayImpl.java:74)
	at com.jogamp.nativewindow.NativeWindowFactory.shutdown(NativeWindowFactory.java:272)
	at com.jogamp.nativewindow.NativeWindowFactory$2$1.run(NativeWindowFactory.java:190)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by skalarproduktraum** [comment]
How did you enter full screen?

**Comment by kephale** [comment]
Not fullscreen, just maximizing the window to fill the screen (still windowed)

**Comment by skalarproduktraum** [comment]
OSX? Linux? Windows?

**Comment by kephale** [comment]
Linux, Ubuntu, 3840x2160 resolution. The JDK has the hiDPI issue as well
(e.g. super small swing UIs). However, the point is that maybe the timeout
should be proportional to the current resolution instead of a fixed value.
I do not get timeouts when the window is not resized (e.g. the default
sciview window size), but when I maximize the window I get a timeout.

**Comment by skalarproduktraum** [comment]
Do you happen to have a longer traceback? The one above is not giving me any useful hints what could be the source.

**Comment by kephale** [comment]
Thats all that it throws....

**Comment by skalarproduktraum** [comment]
Okay, I will try to reproduce this here.

**Comment by skalarproduktraum** [comment]
This was an issue with how the FPSAnimator is destroyed on resize/close and should be fixed with #268. Can you confirm?

**Comment by skalarproduktraum** [comment]
*poke* @kephale

**Comment by kephale** [comment]
Haven't seen this issue

**Comment by skalarproduktraum** [comment]
Then I shall close this for the moment, please feel free to reopen, should it occur again 👍
