### ISSUE TITLE
Issue with generateBoundingBox for sphere?

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#239]
```
java.nio.BufferUnderflowException
	at java.nio.DirectFloatBufferU.get(DirectFloatBufferU.java:271)
	at java.nio.FloatBuffer.get(FloatBuffer.java:715)
	at graphics.scenery.Node.generateBoundingBox(Node.kt:392)
	at sc.iview.SciView.updateFloorPosition(SciView.java:1467)
	at sc.iview.SciView.addNode(SciView.java:1102)
	at sc.iview.SciView.addSphere(SciView.java:904)
	at sc.iview.commands.edit.AddSphere.run(AddSphere.java:64)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by skalarproduktraum** [comment]
That is strange, because in generateBoundingBox(), the vertices are only iterated if the buffer `hasRemaining()`, can you elaborate on what you've did before?

**Comment by kephale** [comment]
Did before? I'm not sure I've tried much addition of primitive objects for
a while.

**Comment by skalarproduktraum** [comment]
No, I mean: what did lead to the exception?

**Comment by kephale** [comment]
Adding multiple objects. I just got it again when adding meshes during a loop from a SciView example that I'm working on. 

Maybe this happens because of a threading issue? If the Node is still being added, but the bounding box gets requested before the Node is completely added to the scene?

**Comment by kephale** [comment]
I wonder if it goes away if bounding box only returns when needsUpdate and dirty are both false

**Comment by kephale** [comment]
Yeah, that fixes it and can be implemented on the SciView side
