### ISSUE TITLE
Creating too many nodes leads to potentially silent failure to allocate memory

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#39]
Resulting in crashes like:

`Caused by: com.jogamp.opengl.GLException: Caught GLException: GL_INVALID_OPERATION: Buffer for target 0x8892 not bound on thread main-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more
Caused by: com.jogamp.opengl.GLException: GL_INVALID_OPERATION: Buffer for target 0x8892 not bound
	at jogamp.opengl.GLBufferObjectTracker.createBufferStorage(GLBufferObjectTracker.java:164)
	at jogamp.opengl.gl4.GL4bcImpl.glBufferData(GL4bcImpl.java:40258)
	at scenery.backends.opengl.OpenGLRenderer.updateVertices(OpenGLRenderer.kt:1389)
	at scenery.backends.opengl.OpenGLRenderer.preDrawAndUpdateGeometryForNode(OpenGLRenderer.kt:582)
	at scenery.backends.opengl.OpenGLRenderer.render(OpenGLRenderer.kt:790)
	at scenery.backends.opengl.OpenGLRenderer.display(OpenGLRenderer.kt:245)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
`

This is just a hypothesis though

**Comment by skalarproduktraum** [comment]
Hey @kephale,

could you please post an example for this? I tried to verify the issue with both a large number of `Box` instances (10000) and the same number of `Mesh` instances, where the latter clearly ran into a OutOfMemory error.

**Comment by skalarproduktraum** [comment]
Removing milestone as this is still pending verification.

**Comment by skalarproduktraum** [comment]
@kephale I'll close this now, as apparently it has not been seen again. Feel free to reopen if it occurs again.
