### ISSUE TITLE
Error when reading Json-File

### ISSUE THREAD

**Issue by Domino2357** [scenerygraphics/scenery#415]
Heyho!
I am trying to read a json file containing the periodic table. The class `PeriodicTable` should parse the file `PubChemElements_all.json`. Both can be found at #414, a7f9e2cb6288f45791f881f43bd6687fd500437a. The error message is the following:
```
Exception in thread "main" com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class graphics.scenery.PeriodicTable$PeriodicTableau] value failed for JSON property thumbnail due to missing (therefore NULL) value for creator parameter thumbnail which is a non-nullable type
 at [Source: (StringReader); line: 2505, column: 1] (through reference chain: graphics.scenery.PeriodicTable$PeriodicTableau["thumbnail"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:112)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402)
	at graphics.scenery.PeriodicTable.<init>(PeriodicTable.kt:37)
	at graphics.scenery.tests.examples.PeriodicTableTest.init(PeriodicTableTest.kt:11)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:221)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:497)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:497)
	at graphics.scenery.tests.examples.PeriodicTableTest$Companion.main(PeriodicTableTest.kt:18)
	at graphics.scenery.tests.examples.PeriodicTableTest.main(PeriodicTableTest.kt)
```

**Comment by skalarproduktraum** [comment]
Hey @Domino2357! If you have a property that doesn't occur always, it needs to be nullable in the data class you define 👍 
E.g., `thumbnai: String?`
