### ISSUE TITLE
Crash when started on windows 10 with a NVIDIA QUADRO RTX 3000

### ISSUE THREAD

**Issue by bpavie** [scenerygraphics/scenery#452]
Dear,

I have just install sciview 0.2 beta via the plugin mechanism on windows 10 with a NVIDIA graphic card RTX 3000 and got the following error when I start sciview via  `Plugins › SciView` and on top of it fiji crash and need to be killed.

```
Started application as PID 14588
This is sciview 0.2.0-beta-9-SNAPSHOT (12709a0d) ) / scenery 0.7.0-beta-8-SNAPSHOT (9747a221) ( (12709a0d)  /  (9747a221))
Resetting language to Python
Loaded Deferred Shading (Deferred Shading, with HDR postprocessing and FXAA)
[ERROR] Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
[ERROR] Could not instantiate renderer. Is your graphics card working properly and do you have the most recent drivers installed?
java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at graphics.scenery.backends.vulkan.VulkanRenderer.createInstance(VulkanRenderer.kt:3868)
	at graphics.scenery.backends.vulkan.VulkanRenderer.<init>(VulkanRenderer.kt:508)
	at graphics.scenery.backends.Renderer$Companion.createRenderer(Renderer.kt:268)
	at graphics.scenery.backends.Renderer$Companion.createRenderer$default(Renderer.kt:250)
	at sc.iview.ui.SwingMainWindow.<init>(SwingMainWindow.kt:205)
	at sc.iview.SciView.init(SciView.kt:382)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:217)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:491)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:491)
	at sc.iview.DefaultSciViewService.lambda$makeSciView$0(DefaultSciViewService.java:114)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at sc.iview.DefaultSciViewService.makeSciView(DefaultSciViewService.java:127)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:175)
	at sc.iview.commands.LaunchViewer.run(LaunchViewer.kt:60)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Call to Creating Vulkan instance failed: Initialization of an object could not be completed for implementation-specific reasons.
	at graphics.scenery.backends.vulkan.VulkanRenderer.createInstance(VulkanRenderer.kt:3868)
	at graphics.scenery.backends.vulkan.VulkanRenderer.<init>(VulkanRenderer.kt:508)
	at graphics.scenery.backends.Renderer$Companion.createRenderer(Renderer.kt:268)
	at graphics.scenery.backends.Renderer$Companion.createRenderer$default(Renderer.kt:250)
	at sc.iview.ui.SwingMainWindow.<init>(SwingMainWindow.kt:205)
	at sc.iview.SciView.init(SciView.kt:382)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:217)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$1.invokeSuspend(SceneryBase.kt:491)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:491)
	at sc.iview.DefaultSciViewService.lambda$makeSciView$0(DefaultSciViewService.java:114)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	... 4 more

```

**Comment by skalarproduktraum** [comment]
Dear @bpavie, do you have the latest drivers from Nvidia installed? This does look like a driver issue.

**Comment by skalarproduktraum** [comment]
@bpavie Any news on that issue?

**Comment by skalarproduktraum** [comment]
Dear @bpavie,

as you've not provided additional info, I'll close this issue. Please reopen if you have more info for us 👍
