### ISSUE TITLE
VR-Setup error whith volumes

### ISSUE THREAD

**Issue by PowerOfNames** [scenerygraphics/scenery#507]
When setting up a VR-Scene with a volume at an initial negative z position, the following error occurs:

[main] ERROR VulkanRenderer - Call to Submit pass rightEye render queue failed: The logical or physical device has been lost.
Exception in thread "main" graphics.scenery.backends.vulkan.VU$VulkanCommandException: Call to Submit pass rightEye render queue failed: The logical or physical device has been lost.
	at graphics.scenery.backends.vulkan.VulkanRenderer$render$1.invokeSuspend(VulkanRenderer.kt:2433)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.backends.vulkan.VulkanRenderer.render(VulkanRenderer.kt:1522)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:223)
	at graphics.scenery.SceneryBase$sceneryMain$1.invokeSuspend(SceneryBase.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:486)
	at graphics.scenery.tests.examples.volumes.VRTransferFunctionEditorExample$Companion.main(VRTransferFunctionEditorExample.kt:223)
	at graphics.scenery.tests.examples.volumes.VRTransferFunctionEditorExample.main(VRTransferFunctionEditorExample.kt)

It only seems to happen then.

**Comment by PowerOfNames** [comment]
Edit: Has nothing todo with the z coordinate -> could be, that if the camera/vr position is within the volumes boundaries, it happens that the renderer decides to quit.

**Comment by skalarproduktraum** [comment]
@moreApi seems to have seen this as well, I will try to reproduce it 👍

**Comment by moreApi** [comment]
`thread {
            //delay volume loading to not crash VR...
            Thread.sleep(1000)
            vol = currentVolume(hub)
            scene.addChild(vol)
        }`

is my workaroudn for this bug
