### ISSUE TITLE
Scenery REPL usage failing in examples

### ISSUE THREAD

**Issue by PowerOfNames** [scenerygraphics/scenery#521]
Currently, in all examples running with wantREPL = true -> getting this error message:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/MapMaker
	at org.python.core.ThreadStateMapping.<clinit>(ThreadStateMapping.java:31)
	at org.python.core.Py.<clinit>(Py.java:1734)
	at org.python.core.PySystemState.<clinit>(PySystemState.java:73)
	at org.python.util.PythonInterpreter.threadLocalStateInterpreter(PythonInterpreter.java:80)
	at org.python.jsr223.PyScriptEngine.<init>(PyScriptEngine.java:27)
	at org.python.jsr223.PyScriptEngineFactory.getScriptEngine(PyScriptEngineFactory.java:85)
	at org.scijava.script.AdaptedScriptLanguage.getScriptEngine(AdaptedScriptLanguage.java:137)
	at org.scijava.script.DefaultScriptInterpreter.<init>(DefaultScriptInterpreter.java:104)
	at org.scijava.script.DefaultScriptInterpreter.<init>(DefaultScriptInterpreter.java:88)
	at org.scijava.script.ScriptREPL.lang(ScriptREPL.java:311)
	at org.scijava.script.ScriptREPL.lang(ScriptREPL.java:300)
	at graphics.scenery.repl.REPL.start(REPL.kt:97)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:167)
	at graphics.scenery.SceneryBase.sceneryMain(SceneryBase.kt)
	at graphics.scenery.SceneryBase$main$4.invokeSuspend(SceneryBase.kt:488)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:488)
	at graphics.scenery.tests.examples.basic.TexturedCubeExample$Companion.main(TexturedCubeExample.kt:60)
	at graphics.scenery.tests.examples.basic.TexturedCubeExample.main(TexturedCubeExample.kt)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.MapMaker
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 26 more
```
	
Examples testes so far: LineExample, EdgeBundlerExample, TexturedCubeExample

**Comment by skalarproduktraum** [comment]
This needs some more details:
* which JDK are you using?
* what platform(s) is this happening on?
* did you try running the tests on the command line (e.g. via `./gradlew LineExample`)

**Comment by skalarproduktraum** [comment]
Okay, as I didn't get any further information on this, I'm closing this. @PowerOfNames please feel free to reopen should you encounter this issue again 👍
