### ISSUE TITLE
Bug in FlybrainOutOfCoreExample

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#589]
**Describe the bug**

When I try to run `FlybrainOutOfCoreExample` on scenery `main` it continuously spams the following warning

```
[main] WARN VolumeManager - Probably ran out of data, corrupt BDV file? java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: pixel and/or image type not supported (yet).
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: pixel and/or image type not supported (yet).
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:78)
	at bvv.core.blocks.TileAccess$Cache.get(TileAccess.java:195)
	at bvv.core.render.VolumeBlocks.canLoadCompletely(VolumeBlocks.java:361)
	at bvv.core.render.VolumeBlocks.getFillTasks(VolumeBlocks.java:345)
	at bvv.core.render.VolumeBlocks.getFillTasks(VolumeBlocks.java:176)
	at graphics.scenery.volumes.VolumeManager.updateBlocks(VolumeManager.kt:397)
	at graphics.scenery.volumes.VolumeManager$createRenderable$1.preDraw(VolumeManager.kt:620)
	at graphics.scenery.backends.vulkan.VulkanRenderer$render$1.invokeSuspend(VulkanRenderer.kt:1603)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.backends.vulkan.VulkanRenderer.render(VulkanRenderer.kt:1526)
	at graphics.scenery.SceneryBase.sceneryMain$suspendImpl(SceneryBase.kt:206)
	at graphics.scenery.SceneryBase$sceneryMain$1.invokeSuspend(SceneryBase.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at graphics.scenery.SceneryBase.main(SceneryBase.kt:485)
	at graphics.scenery.tests.examples.volumes.FlybrainOutOfCoreExample$Companion.main(FlybrainOutOfCoreExample.kt:155)
	at graphics.scenery.tests.examples.volumes.FlybrainOutOfCoreExample.main(FlybrainOutOfCoreExample.kt)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: pixel and/or image type not supported (yet).
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:145)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:74)
	... 29 more
Caused by: java.lang.UnsupportedOperationException: pixel and/or image type not supported (yet).
	at bvv.core.blocks.TileAccess.create(TileAccess.java:130)
	at bvv.core.blocks.TileAccess$Cache.lambda$null$0(TileAccess.java:190)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:135)
	... 31 more
```

**Comment by skalarproduktraum** [comment]
This turned out to be a layer 8 error on the side of @kephale 😂 Closing this.
