### ISSUE TITLE
Colormaps being treated as 3D textures

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#95]
I think this one boils down to the colormaps being read as 3D textures. Jump to the end:

```
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Compiling shaders/Volume.vert to SPIR-V...
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Getting 0 for shaders/Volume.vert (size: 4/4)
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Getting 1 for shaders/Volume.vert (size: 4/4)
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Getting 2 for shaders/Volume.vert (size: 4/4)
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Getting 3 for shaders/Volume.vert (size: 4/4)
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Compiling shaders/Volume.frag to SPIR-V...
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Getting 0 for shaders/Volume.frag (size: 3/3)
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Getting 1 for shaders/Volume.frag (size: 3/3)
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLShaderModule - Getting 2 for shaders/Volume.frag (size: 3/3)
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] WARN OpenGLShaderProgram - There was an issue linking the following shaders:
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] WARN OpenGLShaderProgram - Error produced: GLProgram [mGL=jogamp.opengl.gl4.GL4bcImpl@230c397d, mProgramId=48]
----
Code:
null:
GLShader [mShaderId=46, mShaderType=VertexShader]null:
GLShader [mShaderId=47, mShaderType=FragmentShader]
WARNING: Output of vertex shader '<out Output.inverseProjection>' not read by fragment shader
WARNING: Output of vertex shader '<out Output.inverseModelView>' not read by fragment shader
WARNING: Output of vertex shader '<out Output.textureCoord>' not read by fragment shader
ERROR: Input of fragment shader '<in Input.inverseModelView>' not written by vertex shader
ERROR: Input of fragment shader '<in Input.inverseProjection>' not written by vertex shader
ERROR: Input of fragment shader '<in Input.textureCoord>' not written by vertex shader

[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] WARN OpenGLShaderProgram - VertexShader: #version 410 core
#extension GL_ARB_separate_shader_objects : require

#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct Light
{
    float Linear;
    float Quadratic;
    float Intensity;
    float Radius;
    vec4 Position;
    vec4 Color;
};

 uniform VRParameters
{
    mat4 projectionMatrices[2];
    mat4 headShift;
    float IPD;
    int stereoEnabled;
} vrParameters;

 uniform LightParameters
{
    mat4 ViewMatrix;
    vec3 CamPosition;
    int numLights;
    Light lights[1024];
} _70;

 uniform Matrices
{
    mat4 ModelMatrix;
    mat4 NormalMatrix;
    mat4 ProjectionMatrix;
    int isBillboard;
} ubo;

layout(std140) uniform ShaderProperties
{
    float voxelSizeX;
    float voxelSizeY;
    float voxelSizeZ;
    int sizeX;
    int sizeY;
    int sizeZ;
    float trangemin;
    float trangemax;
    float boxMin_x;
    float boxMin_y;
    float boxMin_z;
    float boxMax_x;
    float boxMax_y;
    float boxMax_z;
    int maxsteps;
    float alpha_blending;
    float gamma;
} _136;

struct currentEye_t
{
    int eye;
};

uniform currentEye_t currentEye;

out Output
{
     vec2 textureCoord;
     mat4 inverseProjection;
     mat4 inverseModelView;
} OutputData;

layout(location = 2) in vec2 vertexTexCoord;
layout(location = 0) in vec3 vertexPosition;
layout(location = 1) in vec3 vertexNormal;

float max3(vec3 v)
{
    return max(max(v.x, v.y), v.z);
}

void main()
{
    mat4 headToEye = vrParameters.headShift;
    headToEye[3].x -= (float(currentEye.eye) * vrParameters.IPD);
    mat4 _79 = (_70.ViewMatrix * float(vrParameters.stereoEnabled ^ 1)) * ubo.ModelMatrix;
    mat4 _90 = ((headToEye * float(vrParameters.stereoEnabled)) * _70.ViewMatrix) * ubo.ModelMatrix;
    mat4 mv = mat4(_79[0] + _90[0], _79[1] + _90[1], _79[2] + _90[2], _79[3] + _90[3]);
    mat4 _111 = ubo.ProjectionMatrix * float(vrParameters.stereoEnabled ^ 1);
    mat4 _119 = vrParameters.projectionMatrices[currentEye.eye] * float(vrParameters.stereoEnabled);
    mat4 projectionMatrix = mat4(_111[0] + _119[0], _111[1] + _119[1], _111[2] + _119[2], _111[3] + _119[3]);
    vec3 L = vec3(float(_136.sizeX), float(_136.sizeY), float(_136.sizeZ)) * vec3(_136.voxelSizeX, _136.voxelSizeY, _136.voxelSizeZ);
    vec3 param = L;
    float Lmax = max3(param);
    mat4 invScale = mat4(vec4(1.0, 0.0, 0.0, 0.0), vec4(0.0, 1.0, 0.0, 0.0), vec4(0.0, 0.0, 1.0, 0.0), vec4(0.0, 0.0, 0.0, 1.0));
    invScale[0].x = Lmax / L.x;
    invScale[1].y = Lmax / L.y;
    invScale[2].z = Lmax / L.z;
    OutputData.inverseProjection = mat4(vec4(1.0, 0.0, 0.0, 0.0), vec4(0.0, 1.0, 0.0, 0.0), vec4(0.0, 0.0, 1.0, 0.0), vec4(0.0, 0.0, 0.0, 1.0));
    OutputData.inverseModelView = mat4(vec4(1.0, 0.0, 0.0, 0.0), vec4(0.0, 1.0, 0.0, 0.0), vec4(0.0, 0.0, 1.0, 0.0), vec4(0.0, 0.0, 0.0, 1.0));
    OutputData.textureCoord = vertexTexCoord;
    gl_Position = vec4(vertexPosition, 1.0);
    gl_Position.z = 2.0 * gl_Position.z - gl_Position.w;
}


[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] WARN OpenGLShaderProgram - FragmentShader: #version 410 core
#extension GL_ARB_separate_shader_objects : require

#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

struct Intersection
{
    bool hit;
    float tnear;
    float tfar;
};

struct Light
{
    float Linear;
    float Quadratic;
    float Intensity;
    float Radius;
    vec4 Position;
    vec4 Color;
};

struct MaterialInfo
{
    vec3 Ka;
    vec3 Kd;
    vec3 Ks;
    float Shininess;
};

layout(std140) uniform ShaderProperties
{
    float voxelSizeX;
    float voxelSizeY;
    float voxelSizeZ;
    int sizeX;
    int sizeY;
    int sizeZ;
    float trangemin;
    float trangemax;
    float boxMin_x;
    float boxMin_y;
    float boxMin_z;
    float boxMax_x;
    float boxMax_y;
    float boxMax_z;
    int maxsteps;
    float alpha_blending;
    float gamma;
} _87;

 uniform LightParameters
{
    mat4 ViewMatrix;
    vec3 CamPosition;
    int numLights;
    Light lights[1024];
} _406;

layout(std140) uniform MaterialProperties
{
    MaterialInfo Material;
    int materialType;
} _410;

 uniform usampler3D VolumeTextures;
 uniform sampler2D ObjectTextures[6];

in Input
{
     vec2 textureCoord;
     mat4 inverseProjection;
     mat4 inverseModelView;
} InputData;

layout(location = 0) out vec4 FragColor;
float PI_r;

Intersection intersectBox(vec4 r_o, vec4 r_d, vec4 boxmin, vec4 boxmax)
{
    vec4 invR = vec4(1.0) / r_d;
    vec4 tbot = invR * (boxmin - r_o);
    vec4 ttop = invR * (boxmax - r_o);
    vec4 tmin = min(ttop, tbot);
    vec4 tmax = max(ttop, tbot);
    float largest_tmin = max(max(tmin.x, tmin.y), max(tmin.x, tmin.z));
    float smallest_tmax = min(min(tmax.x, tmax.y), min(tmax.x, tmax.z));
    return Intersection(smallest_tmax > largest_tmin, largest_tmin, smallest_tmax);
}

void main()
{
    PI_r = 0.3183098137378692626953125;
    float ta = 1.0 / (_87.trangemax - _87.trangemin);
    float tb = _87.trangemin / (_87.trangemin - _87.trangemax);
    vec4 boxMin = vec4(_87.boxMin_x, _87.boxMin_y, _87.boxMin_z, 1.0);
    vec4 boxMax = vec4(_87.boxMax_x, _87.boxMax_y, _87.boxMax_z, 1.0);
    float u = (InputData.textureCoord.x * 2.0) - 1.0;
    float v = (InputData.textureCoord.y * 2.0) - 1.0;
    vec4 front = vec4(u, v, -1.0, 1.0);
    vec4 back = vec4(u, v, 1.0, 1.0);
    vec4 orig0 = InputData.inverseProjection * front;
    orig0 *= (1.0 / orig0.w);
    vec4 orig = InputData.inverseModelView * orig0;
    orig *= (1.0 / orig.w);
    vec4 direc0 = InputData.inverseProjection * back;
    direc0 *= (1.0 / direc0.w);
    vec4 direc = InputData.inverseModelView * normalize(direc0 - orig0);
    direc.w = 0.0;
    vec4 param = orig;
    vec4 param_1 = direc;
    vec4 param_2 = boxMin;
    vec4 param_3 = boxMax;
    Intersection inter = intersectBox(param, param_1, param_2, param_3);
    bool _212 = inter.hit;
    bool _213 = !_212;
    bool _220;
    if (!_213)
    {
        _220 = inter.tfar <= 0.0;
    }
    else
    {
        _220 = _213;
    }
    if (_220)
    {
        FragColor = vec4(1.0, 0.0, 0.0, 1.0);
        return;
    }
    float tnear = max(inter.tnear, 0.0);
    float tfar = inter.tfar;
    float tstep = abs(tnear - tfar) / float(_87.maxsteps);
    vec3 vecstep = direc.xyz * (0.5 * tstep);
    vec3 pos = ((vec3(1.0) + orig.xyz) + (direc.xyz * tnear)) * 0.5;
    vec3 stop = ((vec3(1.0) + orig.xyz) + (direc.xyz * tfar)) * 0.5;
    float maxp = 0.0;
    float mappedVal = 0.0;
    float colVal = 0.0;
    float alphaVal = 0.0;
    float newVal = 0.0;
    if (_87.alpha_blending <= 0.0)
    {
        for (int i = 0; i < _87.maxsteps; i++, pos += vecstep)
        {
            float volume_sample = float(texture(VolumeTextures, pos).x);
            maxp = max(maxp, volume_sample);
        }
        colVal = clamp(pow((ta * maxp) + tb, _87.gamma), 0.0, 1.0);
    }
    else
    {
        float opacity = 1.0;
        for (int i_1 = 0; i_1 < _87.maxsteps; i_1++, pos += vecstep)
        {
            float volume_sample_1 = float(texture(VolumeTextures, pos).x);
            newVal = clamp((ta * volume_sample_1) + tb, 0.0, 1.0);
            colVal = max(colVal, opacity * newVal);
            opacity *= (1.0 - (_87.alpha_blending * clamp(newVal, 0.0, 1.0)));
            if (opacity <= 0.0199999995529651641845703125)
            {
                break;
            }
        }
    }
    alphaVal = clamp(colVal, 0.0, 1.0);
    alphaVal = (alphaVal < 0.00999999977648258209228515625) ? 0.0 : alphaVal;
    vec4 color = texture(ObjectTextures[3], vec2(colVal, 0.5));
    color.w = alphaVal;
    FragColor = color;
}


[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLRenderer - Loading texture /Users/kharrington/git/scenery/src/main/resources/graphics/scenery/volumes/colormap-plasma.png for Volume
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLRenderer - Loading texture fromBuffer:volume for Volume
[SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0] INFO OpenGLRenderer - Copying data from buffer: 8000
Exception in thread "SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught IndexOutOfBoundsException: Required 32000 remaining bytes in buffer, only had 8000 on thread SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught IndexOutOfBoundsException: Required 32000 remaining bytes in buffer, only had 8000 on thread SciJava-7e4fcbc2-Thread-1-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more
Caused by: java.lang.IndexOutOfBoundsException: Required 32000 remaining bytes in buffer, only had 8000
	at com.jogamp.common.nio.Buffers.rangeCheckBytes(Buffers.java:1056)
	at jogamp.opengl.gl4.GL4bcImpl.glTexSubImage3D(GL4bcImpl.java:7979)
	at cleargl.GLTexture.copyFrom(GLTexture.java:482)
	at cleargl.GLTexture.copyFrom(GLTexture.java:501)
	at graphics.scenery.backends.opengl.OpenGLRenderer$loadTexturesForNode$1.accept(OpenGLRenderer.kt:1767)
	at graphics.scenery.backends.opengl.OpenGLRenderer$loadTexturesForNode$1.accept(OpenGLRenderer.kt:53)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at graphics.scenery.backends.opengl.OpenGLRenderer.loadTexturesForNode(OpenGLRenderer.kt:1729)
	at graphics.scenery.backends.opengl.OpenGLRenderer.initializeNode(OpenGLRenderer.kt:1633)
	at graphics.scenery.backends.opengl.OpenGLRenderer.render(OpenGLRenderer.kt:1211)
	at graphics.scenery.backends.opengl.OpenGLRenderer.display(OpenGLRenderer.kt:545)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 7 more
```

The code that leads to this is:

```
Volume v = new Volume();
            v.readFromBuffer(image.getName(),byteBuffer,dimensions[0],dimensions[1],dimensions[2],
                    voxelDimensions[0],voxelDimensions[1],voxelDimensions[2],
                    NativeTypeEnum.UnsignedInt,1);
            //v.getColormaps().put("localplasma", "/Users/kharrington/git/scenery/src/main/resources/graphics/scenery/colormap-plasma.tga");
            v.getColormaps().put("localplasma", "/Users/kharrington/git/scenery/src/main/resources/graphics/scenery/volumes/colormap-plasma.png");
            v.setColormap("localplasma");
```

There were issues loading the resources prepopulated into Volume.colormaps, so I had to do manual pathing to get colormaps to even attempt to load.

**Comment by skalarproduktraum** [comment]
Hey! So this was not TFs getting treated as volumes, but it was just some debugging code left in a volume shader, and a mistake with the naming of the inputs of the shader. It's fixed now and a new snapshot is up for you :) 👍
